import NavBar from './components/NavBar/NavBar'
import Providers from './providers'
import routes from './routes'
import './styles/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Youssef El Gharbaoui - Solution Architect - Portfolio',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning >
            <body>
                <Providers>
                    <NavBar routes={routes}></NavBar>
                    <main>
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    )
}
